### ISSUE TITLE
VSC fail to create development container

### ISSUE THREAD

**Issue by gr8b** [gr8b/zabbix-frontend-module#1]
Development container fails to start with following error:
```sh
[2024-02-28T11:22:54.931Z] #0 41.21 configure: error: Cannot find ldap libraries in /usr/lib/x86_64-linux-gnu/. 
------ 
[2024-02-28T11:22:54.931Z] failed to solve: process "/bin/sh -c apt-get update && export DEBIAN_FRONTEND=noninteractive     && apt-get install -y mariadb-client libmariadb-dev libgettextpo-dev         locales unzip         libfreetype6-dev libjpeg62-turbo-dev libpng-dev         libaio1 libxml2-dev libldap2-dev         automake shtool build-essential libaio-dev libcurl4-openssl-dev libevent-dev libgnutls28-dev         libiksemel-dev libopenipmi-dev libpcre3-dev libsnmp-dev libssh2-1-dev     && apt-get clean -y && rm -rf /var/lib/apt/lists/*     && docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/     && docker-php-ext-install ldap bcmath gettext sockets" did not complete successfully: exit code: 1 
[2024-02-28T11:22:54.936Z] Stop (197788 ms): Run: docker compose --project-name zabbix-module-uitwix_devcontainer -f /workspaces/zabbix-module-uitwix/.devcontainer/docker-compose.yml -f /tmp/devcontainercli-root/docker-compose/docker-compose.devcontainer.build-1709119177146.yml build 
[2024-02-28T11:22:54.943Z] Error: Command failed: docker compose --project-name zabbix-module-uitwix_devcontainer -f /workspaces/zabbix-module-uitwix/.devcontainer/docker-compose.yml -f /tmp/devcontainercli-root/docker-compose/docker-compose.devcontainer.build-1709119177146.yml build 
[2024-02-28T11:22:54.943Z]     at pw (/root/.vscode-remote-containers/dist/dev-containers-cli-0.338.1/dist/spec-node/devContainersSpecCLI.js:429:525) 
[2024-02-28T11:22:54.943Z]     at runMicrotasks (<anonymous>) 
[2024-02-28T11:22:54.943Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5) 
[2024-02-28T11:22:54.943Z]     at async L$ (/root/.vscode-remote-containers/dist/dev-containers-cli-0.338.1/dist/spec-node/devContainersSpecCLI.js:429:2496) 
[2024-02-28T11:22:54.943Z]     at async N$ (/root/.vscode-remote-containers/dist/dev-containers-cli-0.338.1/dist/spec-node/devContainersSpecCLI.js:409:3165) 
[2024-02-28T11:22:54.943Z]     at async tAA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.338.1/dist/spec-node/devContainersSpecCLI.js:481:3833) 
[2024-02-28T11:22:54.943Z]     at async CC (/root/.vscode-remote-containers/dist/dev-containers-cli-0.338.1/dist/spec-node/devContainersSpecCLI.js:481:4775) 
[2024-02-28T11:22:54.943Z]     at async NeA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.338.1/dist/spec-node/devContainersSpecCLI.js:614:11107) 
[2024-02-28T11:22:54.943Z]     at async MeA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.338.1/dist/spec-node/devContainersSpecCLI.js:614:10848) 
[2024-02-28T11:22:54.955Z] Stop (200000 ms): Run in container: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.338.1/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-f2b878eb-1f39-4570-9e1f-52c196eafa291709119170202 --workspace-folder /workspaces/zabbix-module-uitwix --workspace-mount-consistency cached --id-label vsch.local.repository=https://github.com/gr8b/zabbix-module-uitwix.git/tree/main --id-label vsch.local.repository.volume=zabbix-uitwix --id-label vsch.local.repository.folder=zabbix-module-uitwix --id-label devcontainer.config_file=/workspaces/zabbix-module-uitwix/.devcontainer/devcontainer.json --log-level debug --log-format json --config /workspaces/zabbix-module-uitwix/.devcontainer/devcontainer.json --override-config /tmp/devcontainer-92eed33d-5589-44e6-bc0f-741a4d26daef.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=zabbix-uitwix,target=/workspaces,external=true --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default off --mount-workspace-git-root 
[2024-02-28T11:22:54.955Z] Exit code 1 
[2024-02-28T11:22:54.955Z] Start: Run: docker rm -f f3c22a92e1c79d7858c339c7fa910bad8467b9edf71a9f8df4724895065350f7
```
Environment:
- Apple M2 Pro, Sonoma 14.3.1
- Docker desktop 4.28.0 (139021): engine 25.0.3, compose v2.24.6-desktop.1, kubernetes v1.29.1

**Comment by gr8b** [comment]
Fixed in 7e22d8a1f918d7fbd6f1fe3dbb162e9dd4db3977
